### ISSUE TITLE
Splash, Logo Design

### ISSUE THREAD

**Issue by skaengus2012** [skaengus2012/REMINDER_ANDROID#66]
###TODO
- [x] attach splash 
- [x] app name
- [x] app icon 

###Reference 
- [Android referer](https://developer.android.com/develop/ui/views/launch/splash-screen)
- [3-party link](https://sungbin.land/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C12-%EC%8A%A4%ED%94%8C%EB%9E%98%EC%8B%9C-%EB%8C%80%EC%9D%91%ED%95%98%EA%B8%B0-1729f69dc33f)

**Comment by skaengus2012** [comment]
Splash Design 
https://www.figma.com/file/xNYIk8WNlNQU8KKUaud0Qx/NJEL-Timing?type=design&node-id=1272%3A251&mode=design&t=q7U0aJ9GmnKsyEdE-1

**Comment by sawol91** [comment]
App icon
https://www.figma.com/file/xNYIk8WNlNQU8KKUaud0Qx/NJEL-Timing?type=design&node-id=1313%3A85&mode=design&t=zcspfzqhpqWbFqsb-1
