### ISSUE TITLE
Jacoco aggregation for multi module

### ISSUE THREAD

**Issue by skaengus2012** [skaengus2012/REMINDER_ANDROID#95]
Let`s check about this. 

https://medium.com/@gmazzo65/generating-android-jvm-aggregated-coverage-reports-53e912b2e63c

- [x] Make aggregation script 
- [x] Make WIKI
- [x] remove test module

**Comment by skaengus2012** [comment]
Wiki page completed. 
https://github.com/skaengus2012/REMINDER_ANDROID/wiki/Test-CI-(v2)

**Comment by zameelpichen** [comment]
gmazzo has turned it into a plugin!

it will give an "aggregate" gradle task also. (i could find only jacocoTestReport in your current implmentation
